# Generated by Django 3.2.5 on 2021-07-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('job_code', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('certification', models.TextField(blank=True)),
                ('salary', models.CharField(max_length=50)),
                ('industry', models.CharField(choices=[('IT Software', 'IT Software'), ('Finance', 'Finance'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Finance', 'Finance'), ('Education', 'Education'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Manufacturing', 'Manufacturing'), ('Bank', 'Bank'), ('Construction', 'Construction'), ('Tansport', 'Tansport'), ('Telecommunication', 'Telecommunication'), ('Sales', 'Sales'), ('Steel', 'Steel'), ('Trade', 'Trade'), ('Goods', 'Goods'), ('Computer', 'Computer')], max_length=60)),
                ('employment_time', models.CharField(default='Part Time', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'verbose_name_plural': 'JobInfo',
            },
        ),
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resume', models.ImageField(upload_to='resume/%Y/%M/%d')),
                ('experience', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
